[package]
name = "droidloom-camera"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
droidloom-listenfd = { path = "../droidloom-listenfd" }
gstreamer = { version = "0.24.5", features = ["v1_20"] }
gstreamer-app = { version = "0.24.5", features = ["v1_20"] }
gstreamer-video = { version = "0.24.5", features = ["v1_20"] }
rustix = { version = "1.1.4", features = ["net"] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
