/* Copyright 2026 Droidloom. SPDX-License-Identifier: GPL-3.0-or-later */
// Generated by tools/droidloom-systemui-stubs; do not edit.
// AIDL SHA-256: 4a9e4910bfbdf05e22c5fe28dd59af5146daa102afd327a199b8b1b57baf3fa2
package com.android.systemui.compat;

import android.os.*;
import com.android.internal.statusbar.IStatusBar;
import android.app.ITransientNotificationCallback;
import android.app.motioncues.MotionCuesSettings;
import android.content.ComponentName;
import android.graphics.drawable.Icon;
import android.graphics.Rect;
import android.hardware.biometrics.IBiometricContextListener;
import android.hardware.biometrics.IBiometricSysuiReceiver;
import android.hardware.biometrics.PromptInfo;
import android.hardware.fingerprint.IUdfpsRefreshRateRequestCallback;
import android.media.INearbyMediaDevicesProvider;
import android.media.MediaRoute2Info;
import android.media.session.MediaSession;
import android.os.Bundle;
import android.os.ParcelFileDescriptor;
import android.os.UserHandle;
import android.view.KeyEvent;
import android.service.notification.StatusBarNotification;
import com.android.internal.statusbar.DisableStates;
import com.android.internal.statusbar.IAddTileResultCallback;
import com.android.internal.statusbar.IUndoMediaTransferCallback;
import com.android.internal.statusbar.LetterboxDetails;
import com.android.internal.statusbar.StatusBarIcon;
import com.android.internal.view.AppearanceRegion;

public abstract class EmptyStatusBar extends IStatusBar.Stub {
    @Override
    public boolean onTransact(int code, Parcel data, Parcel reply, int flags)
            throws RemoteException {
        int uid = Binder.getCallingUid();
        if (uid != android.os.Process.SYSTEM_UID && uid != 0) {
            throw new SecurityException("SystemUI callbacks require system UID");
        }
        return super.onTransact(code, data, reply, flags);
    }
    @Override public void setIcon(String slot, StatusBarIcon icon) throws RemoteException {}
    @Override public void removeIcon(String slot) throws RemoteException {}
    @Override public void disable(int displayId, int state1, int state2) throws RemoteException {}
    @Override public void disableForAllDisplays(DisableStates disableStates) throws RemoteException {}
    @Override public void animateExpandNotificationsPanel() throws RemoteException {}
    @Override public void animateExpandSettingsPanel(String subPanel) throws RemoteException {}
    @Override public void animateCollapsePanels() throws RemoteException {}
    @Override public void toggleNotificationsPanel() throws RemoteException {}
    @Override public void showWirelessChargingAnimation(int batteryLevel) throws RemoteException {}
    @Override public void setImeWindowStatus(int displayId, int vis, int backDisposition, boolean showImeSwitcherButton) throws RemoteException {}
    @Override public void setWindowState(int display, int window, int state) throws RemoteException {}
    @Override public void showRecentApps(boolean triggeredFromAltTab) throws RemoteException {}
    @Override public void hideRecentApps(boolean triggeredFromAltTab, boolean triggeredFromHomeKey) throws RemoteException {}
    @Override public void toggleRecentApps() throws RemoteException {}
    @Override public void toggleTaskbar() throws RemoteException {}
    @Override public void toggleSplitScreen() throws RemoteException {}
    @Override public void preloadRecentApps() throws RemoteException {}
    @Override public void cancelPreloadRecentApps() throws RemoteException {}
    @Override public void showScreenPinningRequest(int taskId) throws RemoteException {}
    @Override public void confirmImmersivePrompt() throws RemoteException {}
    @Override public void immersiveModeChanged(int rootDisplayAreaId, boolean isImmersiveMode, int windowType) throws RemoteException {}
    @Override public void dismissKeyboardShortcutsMenu() throws RemoteException {}
    @Override public void toggleKeyboardShortcutsMenu(int deviceId) throws RemoteException {}
    @Override public void appTransitionPending(int displayId) throws RemoteException {}
    @Override public void appTransitionCancelled(int displayId) throws RemoteException {}
    @Override public void appTransitionStarting(int displayId, long statusBarAnimationsStartTime, long statusBarAnimationsDuration) throws RemoteException {}
    @Override public void appTransitionFinished(int displayId) throws RemoteException {}
    @Override public void showAssistDisclosure() throws RemoteException {}
    @Override public void startAssist(Bundle args) throws RemoteException {}
    @Override public void onCameraLaunchGestureDetected(int source) throws RemoteException {}
    @Override public void onWalletLaunchGestureDetected() throws RemoteException {}
    @Override public void onEmergencyActionLaunchGestureDetected() throws RemoteException {}
    @Override public void showPictureInPictureMenu() throws RemoteException {}
    @Override public void showGlobalActionsMenu() throws RemoteException {}
    @Override public void showOrHideGlobalActionsMenu() throws RemoteException {}
    @Override public void onProposedRotationChanged(int rotation, boolean isValid) throws RemoteException {}
    @Override public void setTopAppHidesStatusBar(boolean hidesStatusBar) throws RemoteException {}
    @Override public void addQsTile(ComponentName tile) throws RemoteException {}
    @Override public void addQsTileToFrontOrEnd(ComponentName tile, boolean end) throws RemoteException {}
    @Override public void remQsTile(ComponentName tile) throws RemoteException {}
    @Override public void setQsTiles(String[] tiles) throws RemoteException {}
    @Override public void clickQsTile(ComponentName tile) throws RemoteException {}
    @Override public void handleSystemKey(KeyEvent key) throws RemoteException {}
    @Override public void showPinningEnterExitToast(boolean entering) throws RemoteException {}
    @Override public void showPinningEscapeToast() throws RemoteException {}
    @Override public void showShutdownUi(boolean isReboot, String reason) throws RemoteException {}
    @Override public void showAuthenticationDialog(PromptInfo promptInfo, IBiometricSysuiReceiver sysuiReceiver, int[] sensorIds, boolean credentialAllowed, boolean requireConfirmation, int userId, long operationId, String opPackageName, long requestId) throws RemoteException {}
    @Override public void onBiometricAuthenticated(int modality) throws RemoteException {}
    @Override public void onBiometricHelp(int modality, String message) throws RemoteException {}
    @Override public void onBiometricError(int modality, int error, int vendorCode) throws RemoteException {}
    @Override public void hideAuthenticationDialog(long requestId) throws RemoteException {}
    @Override public void setBiometicContextListener(IBiometricContextListener listener) throws RemoteException {}
    @Override public void setUdfpsRefreshRateCallback(IUdfpsRefreshRateRequestCallback callback) throws RemoteException {}
    @Override public void onDisplayAddSystemDecorations(int displayId) throws RemoteException {}
    @Override public void onDisplayRemoveSystemDecorations(int displayId) throws RemoteException {}
    @Override public void onSystemBarAttributesChanged(int displayId, int appearance, AppearanceRegion[] appearanceRegions, boolean navbarColorManagedByIme, int behavior, int requestedVisibleTypes, String packageName, LetterboxDetails[] letterboxDetails) throws RemoteException {}
    @Override public void showTransient(int displayId, int types, boolean isGestureOnSystemBar) throws RemoteException {}
    @Override public void abortTransient(int displayId, int types) throws RemoteException {}
    @Override public void showInattentiveSleepWarning() throws RemoteException {}
    @Override public void dismissInattentiveSleepWarning(boolean animated) throws RemoteException {}
    @Override public void showToast(int uid, String packageName, IBinder token, CharSequence text, IBinder windowToken, int duration, ITransientNotificationCallback callback, int displayId) throws RemoteException {}
    @Override public void hideToast(String packageName, IBinder token) throws RemoteException {}
    @Override public void startTracing() throws RemoteException {}
    @Override public void stopTracing() throws RemoteException {}
    @Override public void suppressAmbientDisplay(boolean suppress) throws RemoteException {}
    @Override public void requestMagnificationConnection(boolean connect) throws RemoteException {}
    @Override public void passThroughShellCommand(String[] args, ParcelFileDescriptor pfd) throws RemoteException {}
    @Override public void setNavigationBarLumaSamplingEnabled(int displayId, boolean enable) throws RemoteException {}
    @Override public void runGcForTest() throws RemoteException {}
    @Override public void requestTileServiceListeningState(ComponentName componentName) throws RemoteException {}
    @Override public void requestAddTile(int callingUid, ComponentName componentName, CharSequence appName, CharSequence label, Icon icon, IAddTileResultCallback callback) throws RemoteException {}
    @Override public void cancelRequestAddTile(String packageName) throws RemoteException {}
    @Override public void updateMediaTapToTransferSenderDisplay(int displayState, MediaRoute2Info routeInfo, IUndoMediaTransferCallback undoCallback) throws RemoteException {}
    @Override public void updateMediaTapToTransferReceiverDisplay(int displayState, MediaRoute2Info routeInfo, Icon appIcon, CharSequence appName) throws RemoteException {}
    @Override public void registerNearbyMediaDevicesProvider(INearbyMediaDevicesProvider provider) throws RemoteException {}
    @Override public void unregisterNearbyMediaDevicesProvider(INearbyMediaDevicesProvider provider) throws RemoteException {}
    @Override public void dumpProto(String[] args, ParcelFileDescriptor pfd) throws RemoteException {}
    @Override public void showRearDisplayDialog(int currentBaseState) throws RemoteException {}
    @Override public void moveFocusedTaskToFullscreen(int displayId) throws RemoteException {}
    @Override public void moveFocusedTaskToStageSplit(int displayId, boolean leftOrTop) throws RemoteException {}
    @Override public void setSplitscreenFocus(boolean leftOrTop) throws RemoteException {}
    @Override public void showMediaOutputSwitcher(String targetPackageName, UserHandle targetUserHandle, MediaSession.Token sessionToken) throws RemoteException {}
    @Override public void moveFocusedTaskToDesktop(int displayId) throws RemoteException {}
    @Override public void startMotionCuesSession(ComponentName componentName, int userId, MotionCuesSettings motionCuesSettings) throws RemoteException {}
    @Override public void endMotionCuesSession() throws RemoteException {}
    @Override public void onDisplayInfoChanged() throws RemoteException {}
    @Override public void onConfigurationChanged() throws RemoteException {}
}
