/* Copyright 2026 Droidloom. SPDX-License-Identifier: GPL-3.0-or-later */
// Generated by tools/droidloom-systemui-stubs; do not edit.
// AIDL SHA-256: 9533992981024ce4cf5c5a92af728f5399b498a9af676bec37458881712b3486
package com.android.systemui.compat;

import android.os.*;
import com.android.internal.policy.IKeyguardService;
import android.content.Intent;
import com.android.internal.policy.IKeyguardDrawnCallback;
import com.android.internal.policy.IKeyguardDismissCallback;
import com.android.internal.policy.IKeyguardStateCallback;
import com.android.internal.policy.IKeyguardExitCallback;
import com.android.internal.policy.KeyguardState;
import android.os.Bundle;

public abstract class EmptyKeyguard extends IKeyguardService.Stub {
    @Override
    public boolean onTransact(int code, Parcel data, Parcel reply, int flags)
            throws RemoteException {
        int uid = Binder.getCallingUid();
        if (uid != android.os.Process.SYSTEM_UID && uid != 0) {
            throw new SecurityException("SystemUI callbacks require system UID");
        }
        return super.onTransact(code, data, reply, flags);
    }
    @Override public void setOccluded(boolean isOccluded) throws RemoteException {}
    @Override public void addStateMonitorCallback(IKeyguardStateCallback callback) throws RemoteException {}
    @Override public void verifyUnlock(IKeyguardExitCallback callback) throws RemoteException {}
    @Override public void dismiss(IKeyguardDismissCallback callback, CharSequence message) throws RemoteException {}
    @Override public void onDreamingStarted() throws RemoteException {}
    @Override public void onDreamingStopped() throws RemoteException {}
    @Override public void onStartedGoingToSleep(int pmSleepReason) throws RemoteException {}
    @Override public void onFinishedGoingToSleep(int pmSleepReason, boolean powerButtonLaunchGestureTriggered) throws RemoteException {}
    @Override public void onStartedWakingUp(int pmWakeReason, boolean powerButtonLaunchGestureTriggered) throws RemoteException {}
    @Override public void onFinishedWakingUp() throws RemoteException {}
    @Override public void onScreenTurningOn(int reason, IKeyguardDrawnCallback callback) throws RemoteException {}
    @Override public void onScreenTurnedOn() throws RemoteException {}
    @Override public void onScreenTurningOff() throws RemoteException {}
    @Override public void onScreenTurnedOff() throws RemoteException {}
    @Override public void setKeyguardEnabled(boolean enabled) throws RemoteException {}
    @Override public void onSystemReady() throws RemoteException {}
    @Override public void doKeyguardTimeout(Bundle options) throws RemoteException {}
    @Override public void setSwitchingUser(boolean switching) throws RemoteException {}
    @Override public void setCurrentUser(int userId) throws RemoteException {}
    @Override public void onBootCompleted() throws RemoteException {}
    @Override public void startKeyguardExitAnimation(long startTime, long fadeoutDuration) throws RemoteException {}
    @Override public void onShortPowerPressedGoHome() throws RemoteException {}
    @Override public void dismissKeyguardToLaunch(Intent intent) throws RemoteException {}
    @Override public void onSystemKeyPressed(int keycode) throws RemoteException {}
    @Override public void showDismissibleKeyguard() throws RemoteException {}
    @Override public void restoreKeyguardState(KeyguardState state, IKeyguardStateCallback stateCallback, IKeyguardDrawnCallback drawnCallback, boolean timeoutRequested, Bundle timeoutOptions) throws RemoteException {}
}
